[package]
name = "wintilex"
description = "Auto-tiling window manager for Windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "wintilex_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
wintilex-core = { path = "../crates/wintilex-core" }
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger = "0.11"
